# show available recipes
default:
    @just --list

# run code formatter
format:
    uvx ruff format ./src/ ./tests/

# run code style checks
style:
    uvx ruff check ./src/ ./tests/

# run unit tests
test:
    uvx pytest -v -p no:cacheprovider --disable-warnings ./tests/

# clean workdir
clean:
    rm -rf ./.pytest_cache ./build ./dist ./src/*.egg-info
