# show available recipes
default:
    @just --list

# run code formatter
format *args:
    uv run ruff format {{ args }} ./src/ ./tests/

# run code style checks
check *args:
    uv run ruff check --config ../ruff.toml {{ args }} ./src/ ./tests/

# run unit tests
test *args:
    uv run -m pytest -v -p no:cacheprovider --disable-warnings {{ args }} ./tests/

# run unit tests with coverage
coverage *args:
    just test --cov=apus_api --cov-branch {{ args }}

# build # build package
build *args:
    uv build --sdist --wheel {{ args }}

# clean workdir
clean:
    rm -rf ./.pytest_cache ./build ./dist ./src/*.egg-info ./cdk.out ./.coverage

# build docker image
docker-build tag='apus-api:latest' *args:
    cd .. && docker build -t {{ tag }} {{ args }} -f ./apus-api/Dockerfile .

# run docker container
docker-run port='8000' tag='apus-api:latest' *args:
    docker run -p {{ port }}:8000 {{ args }} --name apus-api {{ tag }}

# stop docker container
docker-stop:
    docker stop apus-api
    docker rm -f apus-api
