# show available recipes
default:
    @just --list

# run code formatter
format *args:
    uv run ruff format {{ args }} ./src/ ./tests/

# run code style checks
check *args:
    uv run ruff check --config ../ruff.toml {{ args }} ./src/ ./tests/

# run unit tests
test:
    uv run -m pytest -v -p no:cacheprovider --disable-warnings ./tests/

# clean workdir
clean:
    rm -rf ./.pytest_cache ./build ./dist ./src/*.egg-info
