name: 'Continuous Delivery (CD)'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6

      - name: 'Set up Just'
        uses: extractions/setup-just@v3

      - name: 'Set up Python'
        uses: actions/setup-python@v6
        with:
          python-version: 3.9

      - name: 'Install uv'
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: 'Install dependencies'
        run: |
          just sync

      - name: 'Build wheel'
        run: |
          for module in shared api monitoring cli; do
            uv version --package apus-$module ${{ github.ref_name }}
          done
          sed -i "s|vitalibo/apus-api:latest|vitalibo/apus-api:${{ github.ref_name }}|g" apus-api/src/apus_api/cdk/stack.py
          just build

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          path: dist/

      - name: 'Create GitHub release'
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            dist/apus_shared-${{ github.ref_name }}-py3-none-any.whl
            dist/apus_api-${{ github.ref_name }}-py3-none-any.whl
            dist/apus_monitoring-${{ github.ref_name }}-py3-none-any.whl
            dist/apus_cli-${{ github.ref_name }}-py3-none-any.whl

  docker:
    name: 'Docker'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build and push'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apus-api/Dockerfile
          push: true
          tags: 'vitalibo/apus-api:latest,vitalibo/apus-api:${{ github.ref_name }}'
